# 第二章節測驗

## 實訓一 創建數組並進行運算

1. 創建一個數值範圍為0~1,間隔為0.01的數組
2. 創建100個服從正態分布的隨機數
3. 對創建的兩個數組進行四則運算
4. 對創建的隨機數組進行簡單的統計分析

In [1]:
#導入numpy模塊
import numpy as np

In [2]:
#創建數值範圍為0~1,間隔為0.01的數組
arr1=np.arange(0,1,0.01)
print('創建的數組1為:\n',arr1)

創建的數組1為:
 [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


In [4]:
#創建100個服從正態分布的隨機數
arr2=np.random.randn(100)
print('創建的數組2為:\n',arr2)

創建的數組2為:
 [ 0.24325322 -0.15818548 -1.87311481 -1.11488364 -1.79032393 -1.25334807
 -0.19706536 -0.61065115  0.5588148  -1.16595573 -1.57937866 -0.98169169
 -1.25242124 -0.81948422 -0.2960115  -0.16997308 -0.43219168  0.60877108
 -2.50598603 -1.27079641  0.6604246  -0.34200368 -0.67701458  0.63250339
  0.36365564 -0.72413609  0.106109   -0.29526156  0.02637753 -1.32496504
  1.03250183  0.24153484 -0.33881753  0.25256724 -1.78337752 -0.92152261
  1.06893592  1.11218032 -0.46898638  0.60761587  0.51896404  0.19539487
  0.8507728   0.49376454 -1.03641973 -1.16017055 -0.32529599  0.4008287
  0.36142533 -1.04047635  0.39439109 -0.42581708  2.03071985 -0.55107046
 -0.91042526 -0.24478922  1.05310357 -1.95751156  0.29768228 -1.82240985
 -0.39965117 -0.03420238  0.5180524   1.18082976  0.19133784  0.68618939
  0.25153639  0.23043184  1.11162933  2.87986629 -0.53348048 -0.27155589
  0.50906932 -0.90922353  1.40801963 -1.29317449  1.08118054 -1.81025779
  0.57440786  1.23867345  0.2691611   1.22

In [5]:
#對創建的兩個數組進行四則運算
print('兩者相加為:\n',arr1+arr2)

兩者相加為:
 [ 0.24325322 -0.14818548 -1.85311481 -1.08488364 -1.75032393 -1.20334807
 -0.13706536 -0.54065115  0.6388148  -1.07595573 -1.47937866 -0.87169169
 -1.13242124 -0.68948422 -0.1560115  -0.01997308 -0.27219168  0.77877108
 -2.32598603 -1.08079641  0.8604246  -0.13200368 -0.45701458  0.86250339
  0.60365564 -0.47413609  0.366109   -0.02526156  0.30637753 -1.03496504
  1.33250183  0.55153484 -0.01881753  0.58256724 -1.44337752 -0.57152261
  1.42893592  1.48218032 -0.08898638  0.99761587  0.91896404  0.60539487
  1.2707728   0.92376454 -0.59641973 -0.71017055  0.13470401  0.8708287
  0.84142533 -0.55047635  0.89439109  0.08418292  2.55071985 -0.02107046
 -0.37042526  0.30521078  1.61310357 -1.38751156  0.87768228 -1.23240985
  0.20034883  0.57579762  1.1380524   1.81082976  0.83133784  1.33618939
  0.91153639  0.90043184  1.79162933  3.56986629  0.16651952  0.43844411
  1.22906932 -0.17922353  2.14801963 -0.54317449  1.84118054 -1.04025779
  1.35440786  2.02867345  1.0691611   2.0369

In [6]:
print('兩者相減為:\n',arr1-arr2)

兩者相減為:
 [-0.24325322  0.16818548  1.89311481  1.14488364  1.83032393  1.30334807
  0.25706536  0.68065115 -0.4788148   1.25595573  1.67937866  1.09169169
  1.37242124  0.94948422  0.4360115   0.31997308  0.59219168 -0.43877108
  2.68598603  1.46079641 -0.4604246   0.55200368  0.89701458 -0.40250339
 -0.12365564  0.97413609  0.153891    0.56526156  0.25362247  1.61496504
 -0.73250183  0.06846516  0.65881753  0.07743276  2.12337752  1.27152261
 -0.70893592 -0.74218032  0.84898638 -0.21761587 -0.11896404  0.21460513
 -0.4307728  -0.06376454  1.47641973  1.61017055  0.78529599  0.0691713
  0.11857467  1.53047635  0.10560891  0.93581708 -1.51071985  1.08107046
  1.45042526  0.79478922 -0.49310357  2.52751156  0.28231772  2.41240985
  0.99965117  0.64420238  0.1019476  -0.55082976  0.44866216 -0.03618939
  0.40846361  0.43956816 -0.43162933 -2.18986629  1.23348048  0.98155589
  0.21093068  1.63922353 -0.66801963  2.04317449 -0.32118054  2.58025779
  0.20559214 -0.44867345  0.5308389  -0.4169

In [7]:
print('兩者相乘為:\n',arr1*arr2)

兩者相乘為:
 [ 0.00000000e+00 -1.58185482e-03 -3.74622962e-02 -3.34465093e-02
 -7.16129574e-02 -6.26674035e-02 -1.18239216e-02 -4.27455805e-02
  4.47051837e-02 -1.04936016e-01 -1.57937866e-01 -1.07986086e-01
 -1.50290549e-01 -1.06532949e-01 -4.14416099e-02 -2.54959616e-02
 -6.91506689e-02  1.03491084e-01 -4.51077486e-01 -2.41451318e-01
  1.32084920e-01 -7.18207734e-02 -1.48943207e-01  1.45475779e-01
  8.72773526e-02 -1.81034022e-01  2.75883412e-02 -7.97206206e-02
  7.38570904e-03 -3.84239862e-01  3.09750549e-01  7.48757992e-02
 -1.08421611e-01  8.33471889e-02 -6.06348357e-01 -3.22532912e-01
  3.84816931e-01  4.11506717e-01 -1.78214826e-01  2.36970190e-01
  2.07585615e-01  8.01118985e-02  3.57324576e-01  2.12318753e-01
 -4.56024681e-01 -5.22076745e-01 -1.49636156e-01  1.88389490e-01
  1.73484158e-01 -5.09833412e-01  1.97195545e-01 -2.17166712e-01
  1.05597432e+00 -2.92067342e-01 -4.91629639e-01 -1.34634070e-01
  5.89738001e-01 -1.11578159e+00  1.72655720e-01 -1.07522181e+00
 -2.39790700e-01 

In [8]:
print('兩者相除為:\n',arr1/arr2)

兩者相除為:
 [ 0.00000000e+00 -6.32169265e-02 -1.06774021e-02 -2.69086377e-02
 -2.23423255e-02 -3.98931479e-02 -3.04467514e-01 -1.14631734e-01
  1.43160132e-01 -7.71898944e-02 -6.33160385e-02 -1.12051473e-01
 -9.58144084e-02 -1.58636368e-01 -4.72954600e-01 -8.82492700e-01
 -3.70206108e-01  2.79251110e-01 -7.18280140e-02 -1.49512541e-01
  3.02835478e-01 -6.14028476e-01 -3.24956074e-01  3.63634416e-01
  6.59965023e-01 -3.45238975e-01  2.45031042e+00 -9.14443458e-01
  1.06150946e+01 -2.18873699e-01  2.90556385e-01  1.28345875e+00
 -9.44461158e-01  1.30658276e+00 -1.90649482e-01 -3.79806201e-01
  3.36783519e-01  3.32679868e-01 -8.10258064e-01  6.41852885e-01
  7.70766319e-01  2.09831502e+00  4.93668816e-01  8.70860426e-01
 -4.24538426e-01 -3.87874009e-01 -1.41409674e+00  1.17257072e+00
  1.32807516e+00 -4.70938142e-01  1.26777712e+00 -1.19769737e+00
  2.56066833e-01 -9.61764495e-01 -5.93129414e-01 -2.24683099e+00
  5.31761561e-01 -2.91186020e-01  1.94838607e+00 -3.23747153e-01
 -1.50130926e+00 

In [9]:
print('兩者進行冪運算為:\n',arr1 ** arr2)

兩者進行冪運算為:
 [0.00000000e+00 2.07191037e+00 1.52182907e+03 4.98692232e+01
 3.18247834e+02 4.27211992e+01 1.74094104e+00 5.07273540e+00
 2.43798177e-01 1.65694061e+01 3.79645853e+01 8.73085625e+00
 1.42315749e+01 5.32242366e+00 1.78959979e+00 1.38051873e+00
 2.20786605e+00 3.40031819e-01 7.34981997e+01 8.25196420e+00
 3.45448263e-01 1.70531062e+00 2.78733669e+00 3.94721420e-01
 5.95127920e-01 2.72881043e+00 8.66808985e-01 1.47196140e+00
 9.66979781e-01 5.15589256e+00 2.88487326e-01 7.53609093e-01
 1.47117340e+00 7.55774779e-01 6.84778265e+00 2.63118633e+00
 3.35517986e-01 3.30950055e-01 1.57425750e+00 5.64318600e-01
 6.21560556e-01 8.40117343e-01 4.78047162e-01 6.59203826e-01
 2.34170768e+00 2.52541425e+00 1.28737042e+00 7.38868940e-01
 7.66994959e-01 2.10060141e+00 7.60810420e-01 1.33205334e+00
 2.65022259e-01 1.41887267e+00 1.75240902e+00 1.15759439e+00
 5.43020108e-01 3.00523053e+00 8.50308864e-01 2.61578202e+00
 1.22648463e+00 1.01704983e+00 7.80634997e-01 5.79502548e-01
 9.18152656e-

In [10]:
#對隨機數組arr2進行統計分析
print('數組arr2的和為:',np.sum(arr2))

數組arr2的和為: -13.479626618783893


In [11]:
print('數組arr2的均值為:',arr2.mean())

數組arr2的均值為: -0.13479626618783894


In [12]:
print('數組arr2的標準差為:',arr2.std())

數組arr2的標準差為: 1.0272220533605692


In [13]:
print('數組arr2的方差為:',arr2.var())

數組arr2的方差為: 1.055185146910304


In [14]:
print('數組arr2的最小值為:',np.min(arr2))

數組arr2的最小值為: -2.5059860337043998


In [15]:
print('數組arr2的最大值為:',np.max(arr2))

數組arr2的最大值為: 3.0633002266095386


In [16]:
print('數組arr2的最小值索引為:',np.argmin(arr2))

數組arr2的最小值索引為: 18


In [17]:
print('數組arr2的最大值索引為:',np.argmax(arr2))

數組arr2的最大值索引為: 86


In [18]:
#沿著縱軸求和,數組arr2為一維數組,故只有縱軸
print('數組arr2沿著縱軸求和為:',arr2.sum(axis=0))

數組arr2沿著縱軸求和為: -13.479626618783893


In [20]:
#非聚合計算
print('數組arr2的累計和為:\n',np.cumsum(arr2))

數組arr2的累計和為:
 [  0.24325322   0.08506773  -1.78804708  -2.90293072  -4.69325465
  -5.94660272  -6.14366808  -6.75431923  -6.19550444  -7.36146017
  -8.94083883  -9.92253052 -11.17495176 -11.99443598 -12.29044748
 -12.46042056 -12.89261224 -12.28384116 -14.78982719 -16.0606236
 -15.400199   -15.74220268 -16.41921726 -15.78671388 -15.42305824
 -16.14719433 -16.04108532 -16.33634688 -16.30996935 -17.63493439
 -16.60243256 -16.36089772 -16.69971525 -16.44714802 -18.23052554
 -19.15204814 -18.08311222 -16.97093191 -17.43991829 -16.83230242
 -16.31333838 -16.11794351 -15.26717071 -14.77340617 -15.8098259
 -16.96999644 -17.29529243 -16.89446373 -16.5330384  -17.57351475
 -17.17912366 -17.60494075 -15.5742209  -16.12529135 -17.03571661
 -17.28050583 -16.22740226 -18.18491381 -17.88723154 -19.70964139
 -20.10929255 -20.14349494 -19.62544254 -18.44461278 -18.25327494
 -17.56708556 -17.31554917 -17.08511733 -15.97348801 -13.09362172
 -13.6271022  -13.89865809 -13.38958877 -14.29881229 -12.8907926

In [21]:
print('數組arr2的累計積為:\n',np.cumprod(arr2))

數組arr2的累計積為:
 [ 2.43253216e-01 -3.84791272e-02  7.20758229e-02 -8.03561560e-02
  1.43863549e-01 -1.80311102e-01  3.55330721e-02 -2.16983113e-02
 -1.21253374e-02  1.41376067e-02 -2.23286343e-02  2.19198349e-02
 -2.74528667e-02  2.24971911e-02 -6.65942725e-03  1.13192334e-03
 -4.89207853e-04 -2.97815593e-04  7.46321717e-04 -9.48422959e-04
 -6.26361854e-04  2.14218061e-04 -1.45028750e-04 -9.17311759e-05
 -3.33585591e-05  2.41561364e-05  2.56318359e-06 -7.56809580e-07
 -1.99627691e-08  2.64499712e-08  2.73096437e-08  6.59623032e-09
 -2.23491849e-09 -5.64467192e-10  1.00665810e-09 -9.27658197e-10
 -9.91607167e-10 -1.10284597e-09  5.17219745e-10  3.14270926e-10
  1.63095308e-10  3.18679873e-11  2.71124167e-11  1.33871501e-11
 -1.38747064e-11  1.60970257e-11 -5.23629793e-12 -2.09885850e-12
 -7.58580623e-13  7.89285198e-13  3.11287049e-13 -1.32551343e-13
 -2.69174643e-13  1.48334194e-13 -1.35047197e-13  3.30580976e-14
  3.48136007e-14 -6.81480258e-14 -2.02864594e-14  3.69702435e-14
 -1.4775201

## 實訓二 創建一個國際象棋的棋盤

>創建國際棋盤,填充8x8矩陣

1. 創建一個8x8的矩陣
2. 把1.3.5.7列和2.4.6行的元素設為一

In [35]:
#創建8x8矩陣
chess=np.zeros((8,8))
print('創建矩陣為:\n',chess)

創建矩陣為:
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
for i in range(0,7,2):
    for j in range(0,7,2):
        chess[i][j]=1
else:
    for i in range(1,8,2):
        for j in range(1,8,2):
            chess[i][j]=1
            
print('創建的棋盤為:\n',chess)

創建的棋盤為:
 [[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


## 操作題

1. 生成範圍在0~1,服從均勻分布的10列5行數組
2. 生成兩個2x2矩陣,並計算矩陣乘積

In [43]:
#創建範圍在0~1,服從均勻分布的10x5數組
operation1=np.random.rand(10,5)
print('創建的數組為:\n',operation1)

創建的數組為:
 [[0.72027592 0.76394498 0.80696158 0.6209573  0.98740358]
 [0.17106831 0.31630506 0.30175975 0.05571373 0.63554962]
 [0.13300275 0.55950458 0.59201984 0.43851828 0.09773029]
 [0.30989155 0.43368942 0.49389327 0.04113682 0.48771996]
 [0.6138642  0.55022743 0.16740621 0.17398622 0.38870557]
 [0.83092251 0.88291032 0.63205333 0.53964808 0.78888432]
 [0.88447254 0.51900423 0.33125723 0.06730922 0.34875066]
 [0.78653895 0.18898237 0.63606291 0.66794867 0.02665678]
 [0.2191538  0.8477353  0.62292587 0.42063984 0.70621798]
 [0.48033746 0.73085741 0.73026789 0.54177516 0.06735532]]


In [46]:
#生成兩個2*2矩陣
matr1=np.matrix([[2,3],[4,5]])
matr2=np.matrix([[6,7],[8,9]])
print('創建的數組一為:\n',matr1)
print('創建的數組二為:\n',matr2)

創建的數組一為:
 [[2 3]
 [4 5]]
創建的數組二為:
 [[6 7]
 [8 9]]


In [47]:
#計算兩者乘積
print('兩者相乘為:\n',matr1*matr2)

兩者相乘為:
 [[36 41]
 [64 73]]
